### ISSUE TITLE
Пошук не відповідає очікуванням

### ISSUE THREAD

**Issue by Brazilianian** [MITIT-DEP22/schedule#4]
Я виконую пошук, результат не відвовідає очікуванням

Результати пошуку:
![Image](https://github.com/MITIT-DEP22/schedule/assets/88961767/702e64cf-85d5-4e17-86ac-8cbaeec4ff83)

Реальний розклад
![Image](https://github.com/MITIT-DEP22/schedule/assets/88961767/2edac855-f225-47ff-9d46-994007312785)

**Comment by Denis11333** [comment]
Проблеми з парсером туди пишемо issue
